### ISSUE TITLE
어색한 문장 수정 요청(Chapter 5)

### ISSUE THREAD

**Issue by roeniss** [rayleighko/amathon-amplify-FCD#10]
[이 문서](https://github.com/rayleighko/amathon-amplify-FCD/blob/master/lectures/chapter5.md)의 문장이 어색합니다. 람다 부분을 조금만 구체적으로 적어주시면 좋겠습니다.

> 기본 골격은 일반적인 어플리케이션과 다르지 않습니다. 람다를 통해 서버 사이드 로직을 통해 빌드된 클라이언트 사이드 로직을 돌리는 것이죠.

**Comment by rayleighko** [comment]
적용했습니다.
