### ISSUE TITLE
리소스 삭제 관련 언급 추가 요청

### ISSUE THREAD

**Issue by roeniss** [rayleighko/amathon-amplify-FCD#12]
세션 완료 후, CLI 커맨드 또는 AWS 콘솔을 이용한 "전체 리소스를 삭제하는 가이드"가 있으면 좋을 것 같습니다. 꼭 문서 작성이 아니어도 구두로 충분히 전달될 듯 합니다.

**Comment by rayleighko** [comment]
적용했습니다.
