### ISSUE TITLE
codelab 폴더의 README.md 관련 이슈입니다

### ISSUE THREAD

**Issue by nulut** [rayleighko/amathon-amplify-FCD#7]
codelab 폴더 안에 있는 [README.md](http://bitly.kr/i6WS2ct) 내용입니다

> **create-react-app-auth-amplify**에 접속한 후 자신의 계정으로 해당 레포지토리를 포크하세요. 포크한 다음에는 **자신()**의 로컬 환경에 클론하세요.

1. create-react-app-auth-amplify의 링크가 잘못 걸린 것 같은데 확인 부탁드릴 수 있나요:)
코드의 clone 부분 레포 주소와 링크로 걸린 레포 주소가 다르네요ㅜㅜ 

2. 자신 뒤에 오타가 있는 것 같은데 수정하면 좋을 것 같습니다ㅎㅎ

**Comment by rayleighko** [comment]
반영했습니다.
