### ISSUE TITLE
amplify cli가 제대로 작동되지 않을 시 

### ISSUE THREAD

**Issue by Dailyscat** [rayleighko/amathon-amplify-FCD#8]
상황:
create-react-app-auth-amplify를 클론하고 install 후 
amplify configure 시도 시에 amplify 명령어가 존재하지 않는다는 로그 출력 시

해결:
글로벌로 다시 설치하여 시도
`npm install -g @aws-amplify/cli`

**Comment by rayleighko** [comment]
반영했습니다.
